@api = http://localhost:3700

###
### ✅ Así debe estar (con línea en blanco obligatoria)
POST {{api}}/login
Content-Type: application/json

{
    "numero_tarjeta": "4520899596991226",
    "contrasena": "$2b$10$KVQXrPLUUg0I3RP4etXPWeUSwqMdxhVVf4jyPf24BBrWsHkAG5.62",
    "pin": "$2b$10$FqeDvoREWUWYrtrK7CvrOOVwopuKz1HMDODXNkno9nxHZxfyIP1IC"
}


