@api = http://localhost:3700

### ✅ Así debe estar (sin espacios después de la URL, un solo salto antes del body)
PUT {{api}}/cambiar/estado/tarjeta
Content-Type: application/json

{  
    "pin": "777",  
    "nombre_completo": "Jaziel Armando Vargas cHoque",  
    "nuevo_estado": "activa"  
}