@api = http://localhost:3700

### Realizar Retiro
POST {{api}}/retiro
Content-Type: application/json

{
    "numero_tarjeta": "1000282973",
    "pin": "777",
    "monto": 50.00,
    "metodo": "ATM"
}

### Realizar Transferencia
POST {{api}}/transferencia
Content-Type: application/json

{
    "numero_de_cuenta": "01872812992",
    "numero_cuenta_destino": "1000200030004001",
    "monto": 1000000.00,
    "metodo": "web",
    "descripcion": "Por que me da pena"
}

### Realizar Depósito
POST {{api}}/deposito
Content-Type: application/json

{
    "correo": "jazielarmandovargaschoque@gmail.com",
    "numero_tarjeta": "1000282973",
    "monto": 10000000000000000000000000.00,
    "metodo": "ATM",
    "contrasena": "DrXeno79TESLA",
    "pin": "777"
}

### Obtener Transacciones de un Usuario
POST {{api}}/transacciones/usuario
Content-Type: application/json

{
    "nombre_completo": "Jaziel Armando Vargas cHoque",
    "tipo_transaccion": "Transferencia"
}