@api = http://localhost:3700

###
GET {{api}}/usuarios/completo

###
POST {{api}}/usuario/datos
Content-Type: application/json

{
    "nombre_completo": "Jaziel Armando Vargas cHoque"
}

###
POST {{api}}/crear/usuario
Content-Type: application/json

{
    "nombre": "Jaziel Armando",
    "apellido": "Vargas cHoque",
    "direccion": "Calle Falsa 123",
    "telefono": "8929202",
    "edad": 21,
    "correo": "jazielarmandovargaschoque@gmail.com",
    "contrasena": "DrXeno79TESLA",
    "id_rol": 1,
    "numero_cuenta": "01872812992",
    "tipo_cuenta": "ahorro",
    "saldo_inicial": 1000.00,
    "numero_tarjeta": "1000282973",
    "pin": "777",
    "tipo_tarjeta": "debito",
    "fecha_vencimiento": "2025-12-31"
}