@api = http://localhost:3700

###
GET {{api}}/usuarios/completo

###
POST {{api}}/usuario/datos
Content-Type: application/json

{
    "nombre_completo": "Jaziel Armando Vargas cHoque"
}

###
POST {{api}}/crear/usuario
Content-Type: application/json

{
     "nombre": "Carlos",
    "apellido": "Mamani Choque",
    "direccion": "Calle 21 de Enero 456",
    "telefono": "76543210",
    "edad": 25,
    "correo": "carlos.prueba@gmail.com",
    "contrasena": "miPassword123",
    "tipo_tarjeta": "debito",
    "tipo_cuenta": "ahorro"
}